#!/usr/bin/env node
/**
 * build-photos.js
 *
 * 1. Converts any HEIC/HEIF files in assets/photos/ to JPEG using sips (macOS built-in).
 * 2. Deletes the originals after a successful conversion.
 * 3. Injects <img> tags for all web-ready images into index.html between
 *    the PHOTOS:START and PHOTOS:END comment markers.
 *
 * Usage:
 *   node scripts/build-photos.js
 *
 * Run this after dropping new photos into assets/photos/, then commit.
 * sips is pre-installed on every Mac — no npm dependencies needed.
 */

const fs            = require('fs');
const path          = require('path');
const { execSync }  = require('child_process');

const ROOT       = path.join(__dirname, '..');
const PHOTOS_DIR = path.join(ROOT, 'assets', 'photos');
const HTML_FILE  = path.join(ROOT, 'index.html');

const CONVERT_EXTENSIONS = new Set(['.heic', '.heif']);
const WEB_EXTENSIONS     = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif']);

const START_MARKER = '<!-- PHOTOS:START — generated by scripts/build-photos.js, do not edit manually -->';
const END_MARKER   = '<!-- PHOTOS:END -->';

// ── Step 1: Convert HEIC/HEIF → JPEG ────────────────────────────────────────
const allFiles  = fs.readdirSync(PHOTOS_DIR);
const toConvert = allFiles.filter(f => CONVERT_EXTENSIONS.has(path.extname(f).toLowerCase()));

if (toConvert.length > 0) {
  console.log(`Converting ${toConvert.length} HEIC/HEIF file(s) to JPEG…`);
  for (const file of toConvert) {
    const src  = path.join(PHOTOS_DIR, file);
    const dest = path.join(PHOTOS_DIR, path.basename(file, path.extname(file)) + '.jpg');
    try {
      execSync(`sips -s format jpeg "${src}" --out "${dest}"`, { stdio: 'pipe' });
      fs.unlinkSync(src); // remove original after successful conversion
      console.log(`  ✓ ${file} → ${path.basename(dest)}`);
    } catch (err) {
      console.error(`  ✗ Failed to convert ${file}:`, err.message);
    }
  }
}

// ── Step 2: Collect web-ready images ────────────────────────────────────────
const webFiles = fs.readdirSync(PHOTOS_DIR)
  .filter(f => WEB_EXTENSIONS.has(path.extname(f).toLowerCase()))
  .sort(); // deterministic order — rename files to control sequence

if (webFiles.length === 0) {
  console.log('No web-ready images found in assets/photos/ — nothing injected.');
  process.exit(0);
}

// ── Step 3: Inject <img> tags into index.html ────────────────────────────────
const indent  = '        '; // 8 spaces — matches surrounding HTML indentation
const imgTags = webFiles
  .map(f => `${indent}<img src="assets/photos/${f}" alt="" loading="lazy" />`)
  .join('\n');

const block = `${START_MARKER}\n${imgTags}\n        ${END_MARKER}`;

let html = fs.readFileSync(HTML_FILE, 'utf8');

const startIdx = html.indexOf(START_MARKER);
const endIdx   = html.indexOf(END_MARKER);

if (startIdx === -1 || endIdx === -1) {
  console.error('Could not find PHOTOS:START / PHOTOS:END markers in index.html');
  process.exit(1);
}

html = html.slice(0, startIdx) + block + html.slice(endIdx + END_MARKER.length);
fs.writeFileSync(HTML_FILE, html, 'utf8');

console.log(`\n✓ Injected ${webFiles.length} photo(s) into index.html:`);
webFiles.forEach(f => console.log(`  • ${f}`));
