#!/usr/bin/env node
/**
 * build-bio.js
 *
 * Reads assets/write-up/aboutMe.txt, splits on blank lines into paragraphs,
 * wraps each in <p class="identity-bio">, and injects the block into index.html
 * between BIO:START / BIO:END markers.
 *
 * Usage:
 *   node scripts/build-bio.js
 *
 * Run automatically by the pre-commit hook.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT     = path.join(__dirname, '..');
const BIO_FILE = path.join(ROOT, 'assets', 'write-up', 'aboutMe.txt');
const HTML     = path.join(ROOT, 'index.html');

const START = '<!-- BIO:START — generated by scripts/build-bio.js, do not edit manually -->';
const END   = '<!-- BIO:END -->';

// Read + split on blank lines
const raw        = fs.readFileSync(BIO_FILE, 'utf8');
const paragraphs = raw
  .split(/\n{2,}/)
  .map(p => p.replace(/\s+/g, ' ').trim())
  .filter(Boolean);

const indent = '          ';
const inner  = paragraphs
  .map(p => `${indent}<p class="identity-bio">${p}</p>`)
  .join('\n');

const block = `${START}\n${inner}\n${indent}${END}`;

let html = fs.readFileSync(HTML, 'utf8');

const si = html.indexOf(START);
const ei = html.indexOf(END);

if (si === -1 || ei === -1) {
  console.error('✗ Could not find BIO:START / BIO:END markers in index.html');
  process.exit(1);
}

html = html.slice(0, si) + block + html.slice(ei + END.length);
fs.writeFileSync(HTML, html, 'utf8');

console.log(`✓ Injected ${paragraphs.length} paragraph(s) into index.html from aboutMe.txt`);
