#!/usr/bin/env node
/**
 * build-bio.js
 *
 * 1. Reads assets/write-up/hero.txt, treats it as a single tagline paragraph,
 *    and injects it into index.html between HERO:START / HERO:END markers
 *    as a <p class="tagline">.
 *
 * 2. Reads assets/write-up/aboutMe.txt, splits on blank lines into paragraphs,
 *    wraps each in <p class="identity-bio">, and injects the block into index.html
 *    between BIO:START / BIO:END markers.
 *
 * Usage:
 *   node scripts/build-bio.js
 *
 * Run automatically by the pre-commit hook.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT      = path.join(__dirname, '..');
const HERO_FILE = path.join(ROOT, 'assets', 'write-up', 'hero.txt');
const BIO_FILE  = path.join(ROOT, 'assets', 'write-up', 'aboutMe.txt');
const HTML      = path.join(ROOT, 'index.html');

// ── Marker pairs ────────────────────────────────────────────────────────────
const HERO_START = '<!-- HERO:START — generated by scripts/build-bio.js, do not edit manually -->';
const HERO_END   = '<!-- HERO:END -->';

const BIO_START  = '<!-- BIO:START — generated by scripts/build-bio.js, do not edit manually -->';
const BIO_END    = '<!-- BIO:END -->';

// ── Helpers ──────────────────────────────────────────────────────────────────
function inject(html, startMarker, endMarker, innerContent) {
  const si = html.indexOf(startMarker);
  const ei = html.indexOf(endMarker);
  if (si === -1 || ei === -1) {
    console.error(`✗ Could not find markers:\n  ${startMarker}\n  ${endMarker}`);
    process.exit(1);
  }
  return html.slice(0, si) + innerContent + html.slice(ei + endMarker.length);
}

// ── Load HTML once ───────────────────────────────────────────────────────────
let html = fs.readFileSync(HTML, 'utf8');

// ── 1. Hero (hero.txt → single <p class="tagline">) ─────────────────────────
const heroRaw  = fs.readFileSync(HERO_FILE, 'utf8').replace(/\s+/g, ' ').trim();
const heroIndent = '          ';
const heroBlock  =
  `${HERO_START}\n` +
  `${heroIndent}<p class="tagline">${heroRaw}</p>\n` +
  `${heroIndent}${HERO_END}`;

html = inject(html, HERO_START, HERO_END, heroBlock);
console.log('✓ Injected hero paragraph into index.html from hero.txt');

// ── 2. Biography (aboutMe.txt → multiple <p class="identity-bio">) ───────────
const bioRaw     = fs.readFileSync(BIO_FILE, 'utf8');
const paragraphs = bioRaw
  .split(/\n{2,}/)
  .map(p => p.replace(/\s+/g, ' ').trim())
  .filter(Boolean);

const bioIndent = '          ';
const bioInner  = paragraphs
  .map(p => `${bioIndent}<p class="identity-bio">${p}</p>`)
  .join('\n');

const bioBlock =
  `${BIO_START}\n` +
  `${bioInner}\n` +
  `${bioIndent}${BIO_END}`;

html = inject(html, BIO_START, BIO_END, bioBlock);
console.log(`✓ Injected ${paragraphs.length} paragraph(s) into index.html from aboutMe.txt`);

// ── Write once ───────────────────────────────────────────────────────────────
fs.writeFileSync(HTML, html, 'utf8');
