#!/usr/bin/env node
/**
 * build-photos.js
 *
 * Scans assets/photos/ and injects <img> tags into index.html between
 * the PHOTOS:START and PHOTOS:END comment markers.
 *
 * Usage:
 *   node scripts/build-photos.js
 *
 * Run this after adding new photos to assets/photos/, then commit.
 */

const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const PHOTOS_DIR = path.join(ROOT, 'assets', 'photos');
const HTML_FILE  = path.join(ROOT, 'index.html');

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.heic', '.heif']);

const START_MARKER = '<!-- PHOTOS:START — generated by scripts/build-photos.js, do not edit manually -->';
const END_MARKER   = '<!-- PHOTOS:END -->';

// ── Collect image files ──────────────────────────────────────────────────────
const files = fs.readdirSync(PHOTOS_DIR)
  .filter(f => IMAGE_EXTENSIONS.has(path.extname(f).toLowerCase()))
  .sort(); // deterministic order — rename files to control sequence if needed

if (files.length === 0) {
  console.log('No image files found in assets/photos/ — nothing to do.');
  process.exit(0);
}

// ── Build <img> tags ─────────────────────────────────────────────────────────
const indent = '        '; // 8 spaces — matches surrounding HTML indentation
const imgTags = files
  .map(f => `${indent}<img src="assets/photos/${f}" alt="" loading="lazy" />`)
  .join('\n');

const block = `${START_MARKER}\n${imgTags}\n        ${END_MARKER}`;

// ── Inject into index.html ───────────────────────────────────────────────────
let html = fs.readFileSync(HTML_FILE, 'utf8');

const startIdx = html.indexOf(START_MARKER);
const endIdx   = html.indexOf(END_MARKER);

if (startIdx === -1 || endIdx === -1) {
  console.error('Could not find PHOTOS:START / PHOTOS:END markers in index.html');
  process.exit(1);
}

html = html.slice(0, startIdx) + block + html.slice(endIdx + END_MARKER.length);

fs.writeFileSync(HTML_FILE, html, 'utf8');

console.log(`✓ Injected ${files.length} photo(s) into index.html:`);
files.forEach(f => console.log(`  • ${f}`));
