#!/usr/bin/env node
/**
 * build-photos.js
 *
 * 1. Converts HEIC/HEIF → JPEG via sips (macOS built-in).
 * 2. Reads EXIF date + GPS from each image via exiftool.
 * 3. Reverse-geocodes GPS coordinates to a readable place name via
 *    OpenStreetMap Nominatim (free, no API key, 1 req/s rate limit respected).
 * 4. Caches geocode results in assets/photos/metadata.json so repeat builds
 *    don't re-hit the API for photos already processed.
 * 5. Injects <figure> cards (image + hover overlay) into index.html between
 *    the PHOTOS:START and PHOTOS:END comment markers.
 *
 * Usage:
 *   node scripts/build-photos.js
 *
 * Requires: exiftool  (brew install exiftool)
 *           sips      (pre-installed on macOS)
 */

'use strict';

const fs           = require('fs');
const path         = require('path');
const https        = require('https');
const { execSync } = require('child_process');

const ROOT          = path.join(__dirname, '..');
const PHOTOS_DIR    = path.join(ROOT, 'assets', 'photos');
const HTML_FILE     = path.join(ROOT, 'index.html');
const METADATA_FILE = path.join(PHOTOS_DIR, 'metadata.json');

const CONVERT_EXTENSIONS = new Set(['.heic', '.heif']);
const WEB_EXTENSIONS     = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif']);

const START_MARKER = '<!-- PHOTOS:START — generated by scripts/build-photos.js, do not edit manually -->';
const END_MARKER   = '<!-- PHOTOS:END -->';

// ── Helpers ──────────────────────────────────────────────────────────────────

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/** Parse "40 deg 15' 14.98\" N" → decimal degrees */
function dmsToDecimal(dmsStr, ref) {
  const m = dmsStr.match(/(\d+)\s+deg\s+(\d+)'\s+([\d.]+)"/);
  if (!m) return null;
  let dec = parseFloat(m[1]) + parseFloat(m[2]) / 60 + parseFloat(m[3]) / 3600;
  // exiftool returns "West"/"South" or "W"/"S" — normalise to first char
  const dir = (ref || '').charAt(0).toUpperCase();
  if (dir === 'S' || dir === 'W') dec = -dec;
  return dec;
}

/** Format EXIF date "2026:03:15 17:45:33" → "Mar 15, 2026" */
function formatDate(exifDate) {
  if (!exifDate) return null;
  const [datePart] = exifDate.split(' ');
  const [y, m, d]  = datePart.split(':').map(Number);
  return new Date(y, m - 1, d).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric'
  });
}

/** Build a readable location string from a Nominatim address object */
function formatLocation(address) {
  if (!address) return null;
  const city    = address.city || address.town || address.village || address.hamlet;
  const suburb  = address.neighbourhood || address.suburb || address.quarter;
  const state   = address.state;
  const country = address.country_code?.toUpperCase();

  if (country === 'US') {
    // State abbreviations for US
    const stateAbbr = {
      'New York': 'NY', 'New Jersey': 'NJ', 'California': 'CA',
      'Texas': 'TX', 'Florida': 'FL', 'Illinois': 'IL',
      'Pennsylvania': 'PA', 'Massachusetts': 'MA', 'Washington': 'WA',
    };
    const abbr = stateAbbr[state] || state;
    if (suburb && city) return `${suburb}, ${city}`;
    if (city && abbr)   return `${city}, ${abbr}`;
    if (city)           return city;
    return state || 'United States';
  }

  if (city && country) return `${city}, ${country}`;
  return address.country || null;
}

/** HTTP GET → parsed JSON (Promise) */
function fetchJSON(url, headers = {}) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers }, res => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(body)); }
        catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
}

/** Reverse-geocode lat/lon → readable place string via Nominatim */
async function reverseGeocode(lat, lon) {
  const url = `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lon}`;
  const data = await fetchJSON(url, {
    'User-Agent': 'quantumstatic.github.io portfolio builder (personal site)'
  });
  return formatLocation(data?.address);
}

// ── Step 1: Convert HEIC/HEIF → JPEG ────────────────────────────────────────

const allFiles  = fs.readdirSync(PHOTOS_DIR).filter(f => f !== 'metadata.json');
const toConvert = allFiles.filter(f => CONVERT_EXTENSIONS.has(path.extname(f).toLowerCase()));

if (toConvert.length > 0) {
  console.log(`Converting ${toConvert.length} HEIC/HEIF file(s) to JPEG…`);
  for (const file of toConvert) {
    const src  = path.join(PHOTOS_DIR, file);
    const dest = path.join(PHOTOS_DIR, path.basename(file, path.extname(file)) + '.jpg');
    try {
      execSync(`sips -s format jpeg "${src}" --out "${dest}"`, { stdio: 'pipe' });
      fs.unlinkSync(src);
      console.log(`  ✓ ${file} → ${path.basename(dest)}`);
    } catch (err) {
      console.error(`  ✗ Failed to convert ${file}:`, err.message);
    }
  }
}

// ── Step 2: Collect web-ready images ────────────────────────────────────────

const webFiles = fs.readdirSync(PHOTOS_DIR)
  .filter(f => WEB_EXTENSIONS.has(path.extname(f).toLowerCase()))
  .sort();

if (webFiles.length === 0) {
  console.log('No images found in assets/photos/ — nothing to do.');
  process.exit(0);
}

// ── Step 3: Read / update metadata cache ────────────────────────────────────

(async () => {

  const cache = fs.existsSync(METADATA_FILE)
    ? JSON.parse(fs.readFileSync(METADATA_FILE, 'utf8'))
    : {};

  // Find files that need EXIF extraction
  const needsExif = webFiles.filter(f => !cache[f]);

  if (needsExif.length > 0) {
    console.log(`\nReading EXIF for ${needsExif.length} new photo(s)…`);
    const paths  = needsExif.map(f => `"${path.join(PHOTOS_DIR, f)}"`).join(' ');
    const raw    = execSync(
      `exiftool -json -DateTimeOriginal -GPSLatitude -GPSLongitude -GPSLatitudeRef -GPSLongitudeRef ${paths}`,
      { encoding: 'utf8' }
    );
    const exifData = JSON.parse(raw);

    for (const entry of exifData) {
      const file = path.basename(entry.SourceFile);
      const meta = { date: null, location: null };

      // Date
      meta.date = formatDate(entry.DateTimeOriginal);

      // GPS → geocode
      if (entry.GPSLatitude && entry.GPSLongitude) {
        const lat = dmsToDecimal(entry.GPSLatitude,  entry.GPSLatitudeRef  || 'N');
        const lon = dmsToDecimal(entry.GPSLongitude, entry.GPSLongitudeRef || 'E');

        if (lat !== null && lon !== null) {
          try {
            process.stdout.write(`  Geocoding ${file}… `);
            meta.location = await reverseGeocode(lat, lon);
            console.log(meta.location || '(no result)');
            await sleep(1100); // Nominatim: max 1 req/s
          } catch (err) {
            console.log(`failed (${err.message})`);
          }
        }
      }

      cache[file] = meta;
    }

    // Persist updated cache
    fs.writeFileSync(METADATA_FILE, JSON.stringify(cache, null, 2), 'utf8');
    console.log(`  Cache saved → assets/photos/metadata.json`);
  }

  // ── Step 4: Generate <figure> cards ───────────────────────────────────────

  const indent = '        '; // 8 spaces
  const figures = webFiles.map(f => {
    const meta     = cache[f] || {};
    const location = meta.location || '';
    const date     = meta.date     || '';

    const overlay = (location || date)
      ? `\n${indent}  <figcaption class="photo-meta">\n` +
        (location ? `${indent}    <span class="photo-location">${location}</span>\n` : '') +
        (date     ? `${indent}    <span class="photo-date">${date}</span>\n`         : '') +
        `${indent}  </figcaption>`
      : '';

    return (
      `${indent}<figure class="photo-item">\n` +
      `${indent}  <img src="assets/photos/${f}" alt="" loading="lazy" />${overlay}\n` +
      `${indent}</figure>`
    );
  }).join('\n');

  const block = `${START_MARKER}\n${figures}\n        ${END_MARKER}`;

  // ── Step 5: Inject into index.html ────────────────────────────────────────

  let html = fs.readFileSync(HTML_FILE, 'utf8');

  const startIdx = html.indexOf(START_MARKER);
  const endIdx   = html.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1) {
    console.error('\n✗ Could not find PHOTOS:START / PHOTOS:END markers in index.html');
    process.exit(1);
  }

  html = html.slice(0, startIdx) + block + html.slice(endIdx + END_MARKER.length);
  fs.writeFileSync(HTML_FILE, html, 'utf8');

  console.log(`\n✓ Injected ${webFiles.length} photo(s) into index.html:`);
  webFiles.forEach(f => {
    const m = cache[f] || {};
    const info = [m.location, m.date].filter(Boolean).join(' · ');
    console.log(`  • ${f}${info ? `  (${info})` : ''}`);
  });

})();
